version: '3.8'

services:
  livevibe-db:
    container_name: livevibe-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: livevibe
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_USER: livevibe_user
      MYSQL_PASSWORD: livevibe_pass
    volumes:
      - livevibe_data:/var/lib/mysql
      - livevibe_livevibe_data:/var/lib/mysql
    restart: always
    networks:
      - livevibe-network

  livevibe-app:
    build: .
    container_name: livevibe-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://livevibe-db:3306/livevibe
      SPRING_DATASOURCE_USERNAME: livevibe_user
      SPRING_DATASOURCE_PASSWORD: livevibe_pass
    depends_on:
      - livevibe-db
    networks:
      - livevibe-network

volumes:
<<<<<<< HEAD
  livevibe_data:
=======
  livevibe_livevibe_data:
>>>>>>> 9766b43c35ab08a459236f6040a9f258fe8ec28c

networks:
  livevibe-network:
    driver: bridge
